version: "2"
services:
  join_logo_scp_trial:
    container_name: join_logo_scp_trial
    image: join_logo_scp_trial
    build:
      context: .
      dockerfile: ./docker/Dockerfile
#      dockerfile: ./docker/ubuntu19.10/Dockerfile
#      dockerfile: ./docker/cuda:10.0-devel-ubuntu18.04/Dockerfile
#    runtime: nvidia
    volumes:
      - ./JL:/join_logo_scp_trial/JL
      - ./logo:/join_logo_scp_trial/logo
      - ./result:/join_logo_scp_trial/result
      - ./setting:/join_logo_scp_trial/setting
      - ./src:/join_logo_scp_trial/src

