---
name: Builds

on:
  # Even if you tag a release when you create it, push.tag doesn't work.
  # You should use release types: [published].
  # push:
  #   tags:
  #     - 'v*'
  pull_request:
    branches:
      - main
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      rebuild:
        description: "Re build container?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      no-cache:
        description: "Build docker images with no cache"
        default: false
        required: false
        type: boolean

jobs:
  builds:
    name: Container ${{ matrix.type }}
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        type:
          - ubuntu2404
    permissions:
      contents: write
      packages: write
    env:
      TZ: "Asia/Tokyo"

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v4.2.2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: 0

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/naa0yama/join_logo_scp_trial
          flavor: |
            latest=false
            suffix=-${{ matrix.type }}
          tags: |
            type=ref,event=tag,prefix=,enable=true

            # minimal (short sha)
            type=sha,enable=true,prefix=,format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Dockerfile.${{ matrix.type }}
          push: ${{ contains( github.event.pull_request.merged, true ) || inputs.rebuild == 'true' || github.event_name == 'release' }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: ${{ inputs.no-cache == true }}

      - name: jlse test
        run: |
          set -euxo pipefail
          bash dev-build.sh --gh-action "${{ steps.meta.outputs.tags }}"
          BUILD_EXIT_CODE=$?

          if [ $BUILD_EXIT_CODE -eq 0 ]; then
            STATUS="✅ Successed"
          else
            STATUS="❌ Failed"
          fi

          # Action Summary Create
          {
            echo "# test_jlse Summary"
            echo "**Status:** $STATUS"
            echo "**Exit code:** $BUILD_EXIT_CODE"
            echo ""
            echo "\`\`\`bash"
            cat ./source/test_jlse.log
            echo "\`\`\`"
          } >> $GITHUB_STEP_SUMMARY

      - name: Cleanup pre-releases
        uses: actions/github-script@v7.0.1
        if: ${{ github.event.pull_request.merged == true }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |+
            const __prereleases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });
            const prereleases = __prereleases.data

            for (const index in prereleases) {
              if (prereleases[index].prerelease == true || prereleases[index].draft == true) {
                console.log('delete pre-release & draft ' + prereleases[index]['id'] + '\t' + prereleases[index]['name'])

                await github.rest.repos.deleteRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: prereleases[index]['id'],
                });
              }
            }

            console.log('end run')

      - name: Generate new pre-release tag
        if: ${{ github.event.pull_request.merged == true }}
        id: new_tag
        run: |
          set -euo pipefail

          TODAY=$(date +'%y.%m.%d')
          echo "Today's date: ${TODAY}"

          MATCHED_TAGS=$(git tag --sort=creatordate | grep -E "^v[0-9]{2}\.[0-9]{2}\.[0-9]{2}-beta[0-9]+$")
          echo "Matched pre-release tags:"
          echo "${MATCHED_TAGS}"

          PRE_TAG=$(echo "${MATCHED_TAGS}" | tail -n 1)
          echo "Latest pre-release tag: ${PRE_TAG}"

          if [ "${PRE_TAG}" = "" ]; then
            NEW_TAG="v${TODAY}-beta1"
          else
            PRE_TAG_DATE=$(echo "${PRE_TAG}" | cut -d '-' -f 1)
            if [ "$PRE_TAG_DATE" = "v${TODAY}" ]; then
              PRE_TAG_VERSION=$(echo "${PRE_TAG}" | cut -d '-' -f 2 | sed 's/beta//g')
              NEW_TAG="v${TODAY}-beta$((PRE_TAG_VERSION + 1))"
            else
              NEW_TAG="v${TODAY}-beta1"
            fi
          fi
          echo "New tag: ${NEW_TAG}"
          echo "new_tag=${NEW_TAG}" >> $GITHUB_OUTPUT

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event.pull_request.merged == true }}
        with:
          name: ${{ steps.new_tag.outputs.new_tag }}
          tag_name: ${{ steps.new_tag.outputs.new_tag }}
          generate_release_notes: true
          draft: true
          prerelease: false
          make_latest: ${{ env.MAKE_LATEST }}
