---
name: Builds

on:
  push:
    branches-ignore:
      - main
    tags:
    - 'v*'
  pull_request:
    branches:
      - main
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled
  schedule:
    - cron: '00 02 1 * *'
  workflow_dispatch:
    inputs:
      rebuild:
        description: "Re build container?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  builds:
    name: Container ${{ matrix.type }}
    #if: ${{ contains(fromJson('["renovate/", "dev/","revert"]'), github.head_ref) }} || ${{ contains(fromJson('["renovate/", "dev/","revert"]'), github.ref_name) }} || ${{ inputs.rebuild == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      max-parallel: 5
      matrix:
        type:
          - cuda
          - ubuntu2204
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v4.1.4

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/naa0yama/join_logo_scp_trial
          tags: |
            type=semver,enable=true,prefix=,suffix=-${{ matrix.type }},pattern={{version}}
            type=semver,enable=true,prefix=,suffix=-${{ matrix.type }},pattern={{major}}.{{minor}}

            # minimal (short sha)
            type=sha,enable=true,prefix=,suffix=-${{ matrix.type }},format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: Dockerfile.${{ matrix.type }}
          push: true # ${{ contains( github.event.pull_request.merged, true ) || inputs.rebuild == 'true' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
