name: docker-compose

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: compose-run
        shell: bash
        run: |
          cp -r modules/join_logo_scp_trial/JL .
          cp -r modules/join_logo_scp_trial/setting .
          cp -r modules/join_logo_scp_trial/src .
          docker-compose up --build
