name: build docker file

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cp -r modules docker/ubuntu19.10
        docker build . --file docker/ubuntu19.10/Dockerfile --tag my-image-name:$(date +%s)
