---
name: Cleanup container
on:
  # Even if you tag a release when you create it, push.tag doesn't work.
  # You should use release types: [published].
  # push:
  #   tags:
  #     - 'v*'
  release:
    types:
      - published
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          package-name: 'join_logo_scp_trial'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
